services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      OLLAMA_NUM_PARALLEL: "1"
      OLLAMA_NUM_THREADS: "3"
    mem_limit: 5g
    cpus: "3.0"
    command: ["serve"]
    networks:
      - internal

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    depends_on:
      - ollama
    volumes:
      - ollama:/root/.ollama
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    entrypoint: [ "/bin/sh", "-lc" ]
    command: >
      "
        echo 'Waiting for Ollama...' &&
        until wget -qO- http://ollama:11434/api/tags >/dev/null 2>&1; do sleep 1; done &&
        echo 'Pulling models...' &&
        ollama pull $OLLAMA_MODEL &&
        ollama pull $OLLAMA_RAG_GENERATION_MODEL &&
        echo 'Done.'
      "
    restart: "no"
    networks:
      - internal

  postgres:
    image: pgvector/pgvector:pg18
    container_name: portfolio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - internal

  api:
    container_name: portfolio-api
    restart: unless-stopped
    build:
      context: ./apps/api
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}

      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      OLLAMA_BASE_URL: "http://ollama:11434"
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_RAG_GENERATION_MODEL: ${OLLAMA_RAG_GENERATION_MODEL}
      OLLAMA_EMBEDDING_MODEL: ${OLLAMA_EMBEDDING_MODEL}
      OLLAMA_MODERATION_MAX_TOKENS: ${OLLAMA_MODERATION_MAX_TOKENS}
      OLLAMA__RAG_MAX_TOKENS: ${OLLAMA_RAG_MAX_TOKENS}
      OLLAMA_MODERATION_CTX: ${OLLAMA_MODERATION_CTX}
      OLLAMA_RAG_CTX: ${OLLAMA_RAG_CTX}
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE}
      OLLAMA_WARMUP_INTERVAL: ${OLLAMA_WARMUP_INTERVAL}

      ADMIN_API_KEY: ${ADMIN_API_KEY}
      CLIENT_API_KEY: ${CLIENT_API_KEY}

      BREVO_API_KEY: ${BREVO_API_KEY}
      CONTACT_TO_EMAIL: ${CONTACT_TO_EMAIL}
      CONTACT_FROM_EMAIL: ${CONTACT_FROM_EMAIL}
      CONTACT_FROM_NAME: ${CONTACT_FROM_NAME}
      CONTACT_RATE_LIMIT_WINDOW_MS: ${CONTACT_RATE_LIMIT_WINDOW_MS:-60000}
      CONTACT_RATE_LIMIT_MAX: ${CONTACT_RATE_LIMIT_MAX:-10}
    ports:
      - "9909:9909"
    depends_on:
      - postgres
      - ollama
    networks:
      - internal

  web:
    container_name: portfolio-web
    restart: unless-stopped
    build:
      context: ./apps/web
    environment:
      BACKEND_BASE_URL: "http://api:9909/api"
      API_KEY: ${API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - internal

volumes:
  ollama:
  postgres:

networks:
  internal:
    name: internal